paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Obtener todos los productos
      responses:
        "200":
          description: Los productos fueron obetenidos satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la BD
    post:
      tags:
        - Products
      summary: Crear producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/CreateProduct'
      responses:
        "200":
          description: Producto creado satisfactoriamente
          content:
            application/json:
              schema:
                  $ref: '#components/requestBodies/CreateProduct'
        "400":
          description: Envío de información errónea o campos obligatorios sin completar
        "401":
          description: Usuario no identificado, requiere loguearse primero
        "403":
          description: Perfil no autorizado, accion no permitida para este rol
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la BD
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Obtener producto por Id
      parameters:
        - name: pid
          in: path
          required: true
          description: id del producto que se desea solicitar
          schema: 
            $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                  $ref: '#components/schemas/Product'
        "400":
          description: Envío de información errónea (formato de Id incorrecto)
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la BD
    put:
      tags:
        - Products
      summary: Actualizar producto
      parameters:
        - name: pid
          in: path
          required: true
          description: id del producto que se desea solicitar
          schema: 
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/CreateProduct'
      responses:
        "200":
          description: Producto actualizado satisfactoriamente
          content:
            application/json:
              schema:
                  $ref: '#components/requestBodies/CreateProduct'
        "400":
          description: Envío de información errónea (formato de Id incorrecto)
        "401":
          description: Usuario no identificado, requiere loguearse primero
        "403":
          description: Perfil no autorizado, accion no permitida para este rol
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la BD
    delete:
      tags:
        - Products
      summary: Borrar producto
      parameters:
        - name: pid
          in: path
          required: true
          description: id del producto que se desea solicitar
          schema: 
            $type: String
      responses:
        "200":
          description: Producto eliminado con éxito
          content:
            application/json:
              schema:
                  $ref: '#components/schemas/Product'
        "400":
          description: Envío de información errónea (formato de Id incorrecto)
        "401":
          description: Usuario no identificado, requiere loguearse primero
        "403":
          description: Perfil no autorizado, accion no permitida para este rol
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la BD
  /api/products/mockingproducts:
    get:
      tags:
        - Products
      summary: Obtener productos de prueba (Mocks)
      responses:
        "200":
          description: Productos de prueba obetenidos satisfactoriamente de la biblioteca de generacion de datos simulados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, query defectuosa o fallo de conexión con la biblioteca

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo del producto, este campo es único
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad disponible del producto
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
        thumbnails:
          type: Array
          description: links a imagenes del producto
      example:
        _id: 64c45114eaf9863cc308e64d
        title: Producto Prueba
        description: se agrega en DB
        code: "code123"
        price: 50
        stock: 23
        category: prueba
        status: true
        thumbnails: ["src/public/images/img1"]
  requestBodies:
    CreateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        code:
          type: String
          description: Codigo del producto, este campo es único
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad disponible del producto
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Disponibilidad del producto
        thumbnails:
          type: Array
          description: links a imagenes del producto
      example:
        title:  Producto de Prueba
        description: este es un producto de prueba
        code: abc123
        price: 250
        stock: 50
        category: prueba
        status: false
        thumbnails: ["src/public/images/img1", "src/public/images/img2"]